name: Deploy site to AWS

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install dependencies
        uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: true

      - name: Build site
        run: pnpm run prebuild && pnpm run build

      - name: Deploy to AWS        
        if: github.event_name == 'push'
        uses: finale-lua/action-deploy-aws-static-site@v3.3.0
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          domain: finalelua.com
          publish_dir: ./build